### ISSUE TITLE
Manual install instructions fail

### ISSUE THREAD

**Issue by seajay98** [SENSE-Lab-OSU/neuralImplicitSurfaceSAR#1]
When following the steps in the readme for the manual install, the instructions fail at:
"ls ~/miniconda3/envs/DSS3/lib | grep libstdc++.so"
since DSS3 doesn't exist. Changing the environment to "DSS" causes the next two lines to work but then
"ln -s libstdc++.so.6.0.32 libstdc++.so.6"
fails because the file exists.

Without diving deep into what these files are doing, I'm not sure how to address this. Please advice.

**Comment by nithin-pi** [comment]
Can you please share the result of the command :


ls ~/miniconda3/envs/DSS/lib | grep libstdc++.so

Thanks,
Nithin

From: seajay98 ***@***.***>
Sent: Tuesday, September 24, 2024 5:14 PM
To: SENSE-Lab-OSU/neuralImplicitSurfaceSAR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SENSE-Lab-OSU/neuralImplicitSurfaceSAR] Manual install instructions fail (Issue #1)

When following the steps in the readme for the manual install, the instructions fail at: "ls ~/miniconda3/envs/DSS3/lib | grep libstdc++. so" since DSS3 doesn't exist. Changing the environment to "DSS" causes the next two lines to work but then


When following the steps in the readme for the manual install, the instructions fail at:
"ls ~/miniconda3/envs/DSS3/lib | grep libstdc++.so"
since DSS3 doesn't exist. Changing the environment to "DSS" causes the next two lines to work but then
"ln -s libstdc++.so.6.0.32 libstdc++.so.6"
fails because the file exists.

Without diving deep into what these files are doing, I'm not sure how to address this. Please advice.

**Comment by seajay98** [comment]
Here is the output for that:

(DSS) cj.destefani@watt:~/neuralImplicitSurfaceSAR$ ls ~/miniconda3/envs/DSS/lib | grep libstdc++.so
libstdc++.so.6
libstdc++.so.6.0.21
libstdc++.so.6.0.21-gdb.py
libstdc++.so.6.0.33
libstdc++.so.bak

**Comment by nithin-pi** [comment]
> Here is the output for that:
> 
> (DSS) cj.destefani@watt:~/neuralImplicitSurfaceSAR$ ls ~/miniconda3/envs/DSS/lib | grep libstdc++.so libstdc++.so.6 libstdc++.so.6.0.21 libstdc++.so.6.0.21-gdb.py libstdc++.so.6.0.33 libstdc++.so.bak

Thank you. Can you please use this command instead? This is to link the latest version of C++ compiler on your worsktation with the default compiler used in the anaconda environment. 
ln -s libstdc++.so.6.0.33 libstdc++.so.6

**Comment by seajay98** [comment]
Thanks nithin-pi for the help so far! That got me a few steps further, but now I'm stuck on a pytorch install problem. It looks to be related to the same conversation so I'm putting it here too.

Now the "python setup.py install" don't work, and neither does importing torch from python directly. All give this error:
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: /home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
>>>

**Comment by nithin-pi** [comment]
Based on this issue
https://github.com/pytorch/pytorch/issues/43760

can you please try the following
rm libstdc++.so.6
ln -s libstdc++.so.6.0.33 libstdc++.so.6

in case that doesn't work can you repeat the same with libstdc++.so.6.0.21 ?

**Comment by seajay98** [comment]
Hi nithin-pi,

I followed these instructions and also verified that I didn't make a
mistake the first time by repeating the installation from scratch.
The first set of commands you offer gives a new error:

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/__init__.py",
line 189, in <module>
    from torch._C import *
ImportError:
/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so:
undefined symbol: iJIT_IsProfilingActive


and the second set gives the same error as before:

import torch
Traceback (most recent call last):
File "", line 1, in
File
"/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/
*init*.py", line 189, in
from torch._C import *
ImportError:
/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6:
version `CXXABI_1.3.11' not found (required by
/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/libtorch_python.so)

To confirm, I should be in the same directory ~/miniconda3/envs/DSS/lib$ ?
This error is also what I get before trying to link anything.
Does that first error shine any light on the situation for you?

**Comment by seajay98** [comment]
Doing that symbolic link with any of the other files in the environment's
lib folder that start with 'libstdc++' gets this kind of error:
OSError:
/home/cj.destefani/miniconda3/envs/DSS/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6:
invalid ELF header
So those must not be it either.
